# Generated by Django 4.0.5 on 2022-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='Gateway',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='interface',
            name='IP',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='interface',
            name='Mac',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='interface',
            name='Subnet',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='interface',
            name='addr',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
