# Generated by Django 4.0.5 on 2022-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_interface_gateway_interface_ip_interface_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='computer',
            name='free',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='computer',
            name='total',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='computer',
            name='used',
            field=models.FloatField(default=None),
        ),
    ]
