# Generated by Django 4.0.5 on 2022-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_computer_name_alter_computer_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
