# Generated by Django 4.0.5 on 2022-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_alter_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
