# Generated by Django 4.0.5 on 2022-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_interface_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateau_name', models.CharField(max_length=200, verbose_name='Nom du plateau technique')),
            ],
        ),
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automate_name', models.CharField(max_length=200, verbose_name="Nom de l'automate")),
                ('automate_site', models.ManyToManyField(db_column='automate_site', to='computer.plateau', verbose_name="Plateau de l'automate")),
            ],
        ),
    ]
