# Generated by Django 4.0.5 on 2022-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_plateau_automate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Automate',
        ),
        migrations.DeleteModel(
            name='Plateau',
        ),
    ]
