# Generated by Django 4.0.5 on 2022-06-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0008_resultat_free_resultat_total_resultat_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
