# Generated by Django 4.0.5 on 2022-06-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0009_delete_resultat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('total', models.FloatField(default=None)),
                ('free', models.FloatField(default=None)),
                ('used', models.FloatField(default=None)),
            ],
        ),
    ]
