# Generated by Django 4.0.5 on 2022-06-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0010_rendu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Rendu',
        ),
    ]
